// This snippet will mark all system files as reviewed, so they won't block merging if you're using
// Reviewable's default completion condition.  System files are virtual files generated by
// Reviewable to assist with the code review process, and currently include the Commits file that
// shows all commit messages.

// dependencies: lodash4

_.forEach(review.systemFiles, file => {
  _.forEach(file.revisions, rev => {
    rev.reviewed = true;
  });
});

return {
  files: review.files.concat(review.systemFiles)
};
