{
 "title": "General",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Time to first/last review",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  MIN(authored.\"sentAt\") as \"authored time\",\n  MIN(published.\"sentAt\") as \"published time\",\n  EXTRACT(EPOCH FROM MIN(published.\"sentAt\") - MIN(authored.\"sentAt\"))/60 as \"TTFR\",\n  EXTRACT(EPOCH FROM MAX(published.\"sentAt\") - MIN(authored.\"sentAt\"))/60 as \"TTLR\",\n  concat_ws('/', authored.properties->>'owner', authored.properties->>'repo', authored.properties->>'prNumber') AS \"PR\"\nFROM event authored\nJOIN event published\n  ON authored.properties->>'owner' = published.properties->>'owner'\n  AND authored.properties->>'repo' = published.properties->>'repo'\n  AND authored.properties->>'prNumber' = published.properties->>'pullRequest'\nWHERE\n  authored.event = 'Authored Review' AND\n  published.event = 'Published Comments'\nGROUP BY\n  \"PR\"\n\n\n-- SELECT DISTINCT ON (\"PR\") \"sentAt\" as \"time\", concat_ws('/', properties->>'owner', properties->>'repo', properties->>'pullRequest') AS \"PR\"\n-- FROM event\n-- WHERE event = 'Published Comments'\n-- ORDER BY \"PR\", \"time\"\n"
    }
   ]
  },
  {
   "title": "Review creations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('day', \"sentAt\") AS \"time\", \"userUserId\" FROM event WHERE event = 'Authored Review' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Users (that logged in)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', \"sentAt\") AS \"time\", \"userUserId\" AS \"username\", \"userUserId\" AS \"username2\" FROM event LIMIT 50 "
    }
   ]
  }
 ]
}